base_info:
  title: YiYang演算法隨筆 # Site title
  author: YiYang Hung # Author name
  url: https://yyh-603.github.io/ # Site url

style:
 avatar: /images/icon.jpg
 first_screen: 
  enable: true
  background_image: 
   light: /images/background.jpg
   dark: /images/background.jpg
  description: YiYang演算法隨筆
 scroll: progress_bar

menu: #you can customize, i18n files are in the theme's languages folder. fa-regular recommended
  Home: 
    path: / 
    icon: fa-regular fa-house # can be empty
  Archives: 
    path: /archives 
    icon: fa-regular fa-archive # can be empty
  # Status: 
  #   path: https://status.evanluo.top/
  #   icon: fa-regular fa-chart-bar
  # About: 
  #   icon: fa-regular fa-user
  #   submenus:
  #     Me: /about
  #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
  #     Blog: https://www.evanluo.top
  #     Friends: /friends
  # Links: 
  #   icon: fa-regular fa-link
  #   submenus:
  #     Link1: /link1
  #     Link2: /link2
  #     Link3: /link3

home_article:
  date_format: auto | MMM DD YYYY
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 3 # max number of tags shown in home page article block

post:
  word_count:
    enable: true
    wordcount: true  # word count, one article
    min2read: false   # time to read, one article

  # Author label
  author_label:
    enable: false
    auto: true  # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: [ ]

code_block:
  copy: true # enable code copy button
  style: simple # mac | simple

toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false

  # If true, open TOC every time when you enter the article page
  init_open: false

copyright_info:
  enable: false

website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

search:
  path: search.json
  field: post
  content: true
  format: striptags

local_search:
  enable: true
  preload: true

friend_links:
 columns: 2

feed:
  type: atom
  path: atom.xml
  limit: 20

rss:
 enable: true

lazyload:
 enable: true

footer:
  runtime: false # show website running time or not
  start_time: 2022/3/7 00:00:00 # the starting time of your website, format: yyyy/mm/dd hh:mm:ss
  customize:  # customize footer message, can be html code
  icp: # ICP record number of your website, Can be null
    enable: false
    number: # ICP record number
    url: # ICP record url